"""Command-line entrypoints for rendering manifests and printing derived names/paths."""

from __future__ import annotations

import argparse
import os
import shlex
import sys

from .render import render, render_to_yaml
from .instance import Instance
from .cluster import load_cluster
from .spec import load_spec
from .warnings import collect_warnings


def _render(args: argparse.Namespace, *, routing_only: bool = False) -> int:
    user = args.user or os.environ.get("USER") or "dev"
    cluster = _load_cluster(args)
    spec = load_spec(args.spec, cluster)
    _apply_runtime_overrides(spec, args)
    _print_warnings(spec)
    sys.stdout.write(
        render_to_yaml(
            render(spec, user=user, cluster=cluster, routing_only=routing_only),
            header=_manifest_header(args, user=user, routing_only=routing_only),
        )
    )
    return 0


def _load_cluster(args: argparse.Namespace):
    return load_cluster(args.cluster).with_path_overrides(
        user_root=getattr(args, "user_root", None),
        cache_root=getattr(args, "cache_root", None),
        dev_venv=getattr(args, "dev_venv", None),
        dev_source=getattr(args, "dev_source", None),
    )


def _apply_runtime_overrides(spec, args: argparse.Namespace) -> None:
    if getattr(args, "dev", False):
        spec.runtime.dev = True
    if getattr(args, "dev_venv", None):
        spec.runtime.dev_venv = args.dev_venv
    spec.runtime.pre_launch.extend(getattr(args, "pre_launch", None) or [])


def _print_warnings(spec) -> None:
    for warning in collect_warnings(spec):
        print(f"warning[{warning.code}]: {warning.message}", file=sys.stderr)


def _manifest_header(args: argparse.Namespace, *, user: str, routing_only: bool) -> list[str]:
    command = [
        "manifesto",
        "render-routing" if routing_only else "render",
        args.spec,
        "--cluster",
        args.cluster,
        "--user",
        user,
    ]
    if getattr(args, "dev", False):
        command.append("--dev")
    for name in ("user_root", "cache_root", "dev_venv", "dev_source"):
        value = getattr(args, name, None)
        if value:
            command.extend([f"--{name.replace('_', '-')}", value])
    for hook in getattr(args, "pre_launch", None) or []:
        command.extend(["--pre-launch", hook])
    return [
        "Generated by:",
        f"  {shlex.join(command)}",
        "Safe to edit before applying; comments are ignored by kubectl.",
    ]


def _add_render_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("spec")
    parser.add_argument("--cluster", required=True)
    parser.add_argument("--user")
    parser.add_argument("--dev", action="store_true")
    parser.add_argument("--user-root")
    parser.add_argument("--cache-root")
    parser.add_argument("--dev-venv")
    parser.add_argument("--dev-source")
    parser.add_argument("--pre-launch", action="append", default=[])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="manifesto")
    sub = parser.add_subparsers(dest="command", required=True)

    render_parser = sub.add_parser("render")
    _add_render_args(render_parser)
    render_parser.set_defaults(func=lambda args: _render(args, routing_only=False))

    routing_parser = sub.add_parser("render-routing")
    _add_render_args(routing_parser)
    routing_parser.set_defaults(func=lambda args: _render(args, routing_only=True))

    instance_parser = sub.add_parser("instance-id")
    instance_parser.add_argument("spec")
    instance_parser.add_argument("--user")
    instance_parser.set_defaults(func=_instance_id)

    name_parser = sub.add_parser("name")
    name_parser.add_argument("spec")
    name_parser.add_argument("component")
    name_parser.add_argument("--user")
    name_parser.set_defaults(func=_name)

    cache_parser = sub.add_parser("cache-path")
    cache_parser.add_argument("spec")
    cache_parser.add_argument("--cluster", required=True)
    cache_parser.add_argument("--user")
    cache_parser.add_argument("--user-root")
    cache_parser.add_argument("--cache-root")
    cache_parser.add_argument("--dev-venv")
    cache_parser.add_argument("--dev-source")
    cache_parser.set_defaults(func=_cache_path)

    args = parser.parse_args(argv)
    return args.func(args)


def _instance_id(args: argparse.Namespace) -> int:
    user = args.user or os.environ.get("USER") or "dev"
    spec = load_spec(args.spec)
    print(Instance(user=user, release=spec.release).instance_id)
    return 0


def _name(args: argparse.Namespace) -> int:
    user = args.user or os.environ.get("USER") or "dev"
    spec = load_spec(args.spec)
    print(Instance(user=user, release=spec.release).name(args.component))
    return 0


def _cache_path(args: argparse.Namespace) -> int:
    user = args.user or os.environ.get("USER") or "dev"
    cluster = _load_cluster(args)
    spec = load_spec(args.spec)
    instance = Instance(user=user, release=spec.release)
    print(
        cluster.cache_root(
            user=instance.user_slug,
            release=instance.release_slug,
            gpu_arch=spec.cache.gpu_arch,
            cuda=spec.cache.cuda,
            vllm_version=spec.cache.vllm_version,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
