"""CLI regression tests for derived paths, overrides, and routing-only rendering."""

from pathlib import Path

from manifesto.cli import main
from manifesto.cluster import load_cluster
import manifesto.workflow as workflow
from manifesto.workflow import config_home, resolve_cluster, resolve_model


ROOT = Path(__file__).resolve().parents[1]
MODEL = ROOT / "models" / "deepseek-v4" / "1P-EP8-1D-EP8.yaml"
STANDALONE_MODEL = ROOT / "models" / "qwen" / "aggregated.yaml"
CLUSTER = ROOT / "clusters" / "oci-gb200.yaml"


def test_user_config_catalog_resolves_models_and_clusters(monkeypatch, tmp_path):
    user_config = tmp_path / "manifesto-config"
    model = user_config / "models" / "model_provider" / "model.yaml"
    cluster = user_config / "clusters" / "local.yaml"
    model.parent.mkdir(parents=True)
    cluster.parent.mkdir(parents=True)
    model.write_text("release: local\n")
    cluster.write_text("name: local\n")
    monkeypatch.setenv("MANIFESTO_CONFIG_HOME", str(user_config))

    assert config_home() == user_config
    assert resolve_model("model_provider/model") == str(model)
    assert resolve_cluster("local") == str(cluster)


def test_cluster_named_for_current_context_is_selected(monkeypatch, tmp_path):
    user_config = tmp_path / "manifesto-config"
    cluster = user_config / "clusters" / "local-context.yaml"
    cluster.parent.mkdir(parents=True)
    cluster.write_text("name: local\n")
    monkeypatch.setenv("MANIFESTO_CONFIG_HOME", str(user_config))
    monkeypatch.delenv("MANIFESTO_CLUSTER", raising=False)
    monkeypatch.delenv("MANIFESTO_CLUSTER_MAP", raising=False)
    monkeypatch.setattr(
        workflow,
        "capture",
        lambda cmd, **_: "local-context\n" if cmd[-1] == "current-context" else "kube-cluster\n",
    )

    assert resolve_cluster() == str(cluster)


def test_render_accepts_user_catalog_names(monkeypatch, tmp_path, capsys):
    user_config = tmp_path / "manifesto-config"
    model = user_config / "models" / "local-model.yaml"
    cluster = user_config / "clusters" / "local-cluster.yaml"
    model.parent.mkdir(parents=True)
    cluster.parent.mkdir(parents=True)
    model.write_text(STANDALONE_MODEL.read_text())
    cluster.write_text(CLUSTER.read_text())
    monkeypatch.setenv("MANIFESTO_CONFIG_HOME", str(user_config))

    rc = main(["render", "local-model", "--cluster", "local-cluster", "--namespace", "test", "--user", "tester"])

    assert rc == 0
    assert "kind: Deployment" in capsys.readouterr().out


def test_cache_path_cli_accepts_cluster_template_override(capsys):
    rc = main(
        [
            "cache-path",
            str(MODEL),
            "--cluster",
            str(CLUSTER),
            "--user",
            "Tester.Name",
            "--cache-root",
            "/tmp/cache/{user}/{release}/{cuda}",
        ]
    )

    assert rc == 0
    assert capsys.readouterr().out.strip() == "/tmp/cache/tester-name/wide-ep-1p-ep8-1d-ep8/cu13"


def test_log_path_cli_accepts_cluster_template_override(capsys):
    rc = main(
        [
            "log-path",
            str(MODEL),
            "--cluster",
            str(CLUSTER),
            "--user",
            "Tester.Name",
            "--role",
            "prefill",
            "--log-root",
            "/logs/{user}/{release}",
        ]
    )

    assert rc == 0
    assert capsys.readouterr().out.strip() == "/logs/tester-name/wide-ep-1p-ep8-1d-ep8/prefill"


def test_render_cli_dev_venv_override(monkeypatch, capsys):
    monkeypatch.setenv("MANIFESTO_NAMESPACE", "workload-ns")
    rc = main(
        [
            "render",
            str(MODEL),
            "--cluster",
            str(CLUSTER),
            "--user",
            "tester",
            "--dev",
            "--dev-venv",
            "/custom/venv",
        ]
    )

    assert rc == 0
    assert "name: MANIFESTO_VLLM_DEV_VENV\n            value: /custom/venv" in capsys.readouterr().out


def test_render_cli_prefixes_manifest_with_generation_command(monkeypatch, capsys):
    monkeypatch.setenv("MANIFESTO_NAMESPACE", "workload-ns")
    rc = main(
        [
            "render",
            str(MODEL),
            "--cluster",
            str(CLUSTER),
            "--user",
            "tester",
            "--dev",
        ]
    )

    assert rc == 0
    out = capsys.readouterr().out
    assert out.startswith("# Generated by:\n")
    assert f"#   manifesto render {MODEL} --cluster {CLUSTER} --namespace workload-ns --user tester --dev\n" in out
    assert "# Source: https://github.com/tlrmchlsmth/llm-manifesto\n" in out
    assert "# Safe to edit before applying.\n" in out
    assert "comments are ignored by kubectl" not in out
    assert "\n---\napiVersion: v1\nkind: ServiceAccount\n" in out


def test_render_cli_namespace_override(capsys):
    rc = main(
        [
            "render-routing",
            str(MODEL),
            "--cluster",
            str(CLUSTER),
            "--namespace",
            "workload-ns",
            "--user",
            "tester",
        ]
    )

    assert rc == 0
    assert "--pool-namespace=workload-ns" in capsys.readouterr().out


def test_render_cli_pre_launch_hook(monkeypatch, capsys):
    monkeypatch.setenv("MANIFESTO_NAMESPACE", "workload-ns")
    rc = main(
        [
            "render",
            str(MODEL),
            "--cluster",
            str(CLUSTER),
            "--user",
            "tester",
            "--pre-launch",
            "echo cli-hook",
        ]
    )

    assert rc == 0
    assert "echo cli-hook" in capsys.readouterr().out


def test_render_file_uses_env_defaults(tmp_path, monkeypatch, capsys):
    output = tmp_path / "manifest.yaml"
    monkeypatch.setenv("MANIFESTO_CLUSTER", str(CLUSTER))
    monkeypatch.setenv("MANIFESTO_NAMESPACE", "workload-ns")
    monkeypatch.setenv("USER", "tester")

    rc = main(["render-file", str(MODEL), "--output", str(output), "--dev"])

    assert rc == 0
    assert capsys.readouterr().out.strip() == str(output)
    rendered = output.read_text()
    assert f"#   manifesto render {MODEL} --cluster {CLUSTER} --namespace workload-ns --user tester --dev\n" in rendered
    assert "namespace: workload-ns" in rendered


def test_deploy_pipes_rendered_manifest_to_kubectl(monkeypatch):
    calls = []

    def fake_run(cmd, *, input_text=None):
        calls.append((cmd, input_text))
        return 0

    monkeypatch.setenv("MANIFESTO_CLUSTER", str(CLUSTER))
    monkeypatch.setenv("MANIFESTO_NAMESPACE", "workload-ns")
    monkeypatch.setenv("USER", "tester")
    monkeypatch.setattr(workflow, "run", fake_run)

    rc = main(["deploy", str(MODEL), "--dev"])

    assert rc == 0
    assert calls[0][0] == ["kubectl", "-n", "workload-ns", "apply", "-f", "-"]
    assert "kind: LeaderWorkerSet" in calls[0][1]
    assert "--dev" in calls[0][1]


def test_ready_waits_for_spec_roles_only(monkeypatch, tmp_path):
    spec_file = tmp_path / "aggregated.yaml"
    spec_file.write_text(
        "release: smoke\n"
        "topology: aggregated\n"
        "model: {id: model, image: image}\n"
        "routing: {kind: disabled}\n"
        "roles:\n"
        "  - name: decode\n"
        "    lws: {size: 1}\n"
        "    parallelism: {tp: 1, dp: false, ep: false}\n"
    )
    popen_cmds = []

    class FakeProc:
        def wait(self):
            return 0

    monkeypatch.setenv("MANIFESTO_NAMESPACE", "workload-ns")
    monkeypatch.setattr(workflow.subprocess, "Popen", lambda cmd: popen_cmds.append(cmd) or FakeProc())

    rc = main(["ready", str(spec_file), "--user", "tester"])

    assert rc == 0
    joined = [" ".join(cmd) for cmd in popen_cmds]
    assert any("llm-d.ai/role=decode" in cmd for cmd in joined)
    assert not any("llm-d.ai/role=prefill" in cmd for cmd in joined)
    # Routing is disabled, so no endpoint picker wait is issued.
    assert not any("deploy/" in cmd for cmd in joined)


def test_ready_uses_gateway_class_from_cluster(monkeypatch):
    popen_cmds = []
    capture_cmds = []

    class FakeProc:
        def wait(self):
            return 0

    cluster = load_cluster(CLUSTER)
    cluster.gateway.class_name = "platform-gateway"
    monkeypatch.setenv("MANIFESTO_NAMESPACE", "workload-ns")
    monkeypatch.setattr(workflow, "load_cluster_with_overrides", lambda *_: cluster)
    monkeypatch.setattr(workflow.subprocess, "Popen", lambda cmd: popen_cmds.append(cmd) or FakeProc())
    monkeypatch.setattr(
        workflow,
        "capture",
        lambda cmd, **_: capture_cmds.append(cmd) or '{"data":[{"id":"model"}]}',
    )

    rc = main(["ready", str(MODEL), "--cluster", "cluster.yaml", "--user", "tester"])

    assert rc == 0
    assert popen_cmds
    gateway_url = capture_cmds[0][-1]
    assert gateway_url.endswith("-platform-gateway:80/v1/models")
    assert len(gateway_url.removeprefix("http://").removesuffix(":80/v1/models")) <= 63


def test_apply_file_does_not_require_cluster(monkeypatch, tmp_path):
    output = tmp_path / "manifest.yaml"
    calls = []

    def fake_run(cmd, *, input_text=None):
        calls.append((cmd, input_text))
        return 0

    monkeypatch.delenv("MANIFESTO_CLUSTER", raising=False)
    monkeypatch.delenv("MANIFESTO_CLUSTER_MAP", raising=False)
    monkeypatch.setenv("MANIFESTO_NAMESPACE", "workload-ns")
    monkeypatch.setenv("USER", "tester")
    monkeypatch.setattr(workflow, "run", fake_run)

    rc = main(["apply", "--output", str(output)])

    assert rc == 0
    assert calls == [(["kubectl", "-n", "workload-ns", "apply", "-f", str(output)], None)]
